### ISSUE TITLE
Poseidion `Hash` is broken (2)!

### ISSUE THREAD

**Issue by ed255** [iden3/go-iden3-crypto#10]
Poseidon `Hash` adds 0 value elements as padding to work in multiples of 5 elements.  This means that creating a collision is trivial: H(x) == H(x, 0) == H(x, 0, 0) == ...

 This is checked in the TestPoseidonBrokenPadding, which currently doesn't pass.

**Comment by arnaucube** [comment]
Closing as this was fixed in https://github.com/iden3/go-iden3-crypto/pull/12
