### ISSUE TITLE
Poseidon `Hash` function is broken!

### ISSUE THREAD

**Issue by ed255** [iden3/go-iden3-crypto#9]
The `Hash` function in poseidon for arbitrary length inputs is calculated like this:
```
r_0 = 0
r_(i+1) = r_i + hash(a_(i_0), ..., a_(i_4))
output = r_(n+1)
```

This means that creating a collision is trivial, since any group of 5 elements aligned at 5 elements can be swapped by another group of 5 elements aligned at 5 elements leading to the same hash result.  This is checked in the `TestPoseidonBrokenChunks`, which currently doesn't pass. 

Let's discuss a solution.

**Comment by arnaucube** [comment]
Right! Should be using https://github.com/HarryR/ethsnarks/issues/161#issuecomment-529148986

**Comment by arnaucube** [comment]
https://github.com/iden3/go-iden3-crypto/commit/fcb586591ab6b1d50a9eff5b7a3e93655e62fef8
